" Name:        Gobbie Gob Goo
" Description: A dark theme with a bit of light
" Author:      Vincent Kempers
" License:     MIT
" Note:        Generated by scripts/build.mjs from src/ — edit there, not here.

hi clear
if exists('syntax_on')
  syntax reset
endif
set background=dark
let g:colors_name = 'gobbie-gob-goo'

hi Normal guifg=#c5c8c6 guibg=#252c38 guisp=NONE gui=NONE ctermfg=251 ctermbg=236 cterm=NONE
hi NormalFloat guifg=#c5c8c6 guibg=#1f252f guisp=NONE gui=NONE ctermfg=251 ctermbg=235 cterm=NONE
hi FloatBorder guifg=#373b41 guibg=#1f252f guisp=NONE gui=NONE ctermfg=237 ctermbg=235 cterm=NONE
hi Cursor guifg=#252c38 guibg=#ffffff guisp=NONE gui=NONE ctermfg=236 ctermbg=231 cterm=NONE
hi lCursor guifg=#252c38 guibg=#ffffff guisp=NONE gui=NONE ctermfg=236 ctermbg=231 cterm=NONE
hi CursorIM guifg=#252c38 guibg=#ffffff guisp=NONE gui=NONE ctermfg=236 ctermbg=231 cterm=NONE
hi TermCursor guifg=#252c38 guibg=#ffffff guisp=NONE gui=NONE ctermfg=236 ctermbg=231 cterm=NONE
hi CursorLine guifg=NONE guibg=#2d333c guisp=NONE gui=NONE ctermfg=NONE ctermbg=237 cterm=NONE
hi CursorColumn guifg=NONE guibg=#2d333c guisp=NONE gui=NONE ctermfg=NONE ctermbg=237 cterm=NONE
hi ColorColumn guifg=NONE guibg=#282a2e guisp=NONE gui=NONE ctermfg=NONE ctermbg=235 cterm=NONE
hi LineNr guifg=#6d7278 guibg=#252c38 guisp=NONE gui=NONE ctermfg=243 ctermbg=236 cterm=NONE
hi CursorLineNr guifg=#c5c8c6 guibg=#2d333c guisp=NONE gui=NONE ctermfg=251 ctermbg=237 cterm=NONE
hi SignColumn guifg=NONE guibg=#252c38 guisp=NONE gui=NONE ctermfg=NONE ctermbg=236 cterm=NONE
hi FoldColumn guifg=#7f7f7f guibg=#252c38 guisp=NONE gui=NONE ctermfg=244 ctermbg=236 cterm=NONE
hi Folded guifg=#7f7f7f guibg=#1f252f guisp=NONE gui=italic ctermfg=244 ctermbg=235 cterm=italic
hi VertSplit guifg=#191e26 guibg=#191e26 guisp=NONE gui=NONE ctermfg=234 ctermbg=234 cterm=NONE
hi WinSeparator guifg=#191e26 guibg=#191e26 guisp=NONE gui=NONE ctermfg=234 ctermbg=234 cterm=NONE
hi EndOfBuffer guifg=#252c38 guibg=NONE guisp=NONE gui=NONE ctermfg=236 ctermbg=NONE cterm=NONE
hi NonText guifg=#373b41 guibg=NONE guisp=NONE gui=NONE ctermfg=237 ctermbg=NONE cterm=NONE
hi SpecialKey guifg=#373b41 guibg=NONE guisp=NONE gui=NONE ctermfg=237 ctermbg=NONE cterm=NONE
hi Whitespace guifg=#373b41 guibg=NONE guisp=NONE gui=NONE ctermfg=237 ctermbg=NONE cterm=NONE
hi Conceal guifg=#7f7f7f guibg=NONE guisp=NONE gui=NONE ctermfg=244 ctermbg=NONE cterm=NONE
hi Visual guifg=NONE guibg=#4c4f57 guisp=NONE gui=NONE ctermfg=NONE ctermbg=239 cterm=NONE
hi VisualNOS guifg=NONE guibg=#4c4f57 guisp=NONE gui=NONE ctermfg=NONE ctermbg=239 cterm=NONE
hi Search guifg=NONE guibg=#716c5d guisp=NONE gui=NONE ctermfg=NONE ctermbg=242 cterm=NONE
hi IncSearch guifg=#252c38 guibg=#ffe2a1 guisp=NONE gui=NONE ctermfg=236 ctermbg=223 cterm=NONE
hi CurSearch guifg=#252c38 guibg=#ffe2a1 guisp=NONE gui=NONE ctermfg=236 ctermbg=223 cterm=NONE
hi Substitute guifg=#252c38 guibg=#fda1aa guisp=NONE gui=NONE ctermfg=236 ctermbg=217 cterm=NONE
hi MatchParen guifg=#a4d8d1 guibg=#38464f guisp=NONE gui=bold ctermfg=152 ctermbg=238 cterm=bold
hi Pmenu guifg=#c5c8c6 guibg=#1f252f guisp=NONE gui=NONE ctermfg=251 ctermbg=235 cterm=NONE
hi PmenuSel guifg=#ffffff guibg=#373b41 guisp=NONE gui=bold ctermfg=231 ctermbg=237 cterm=bold
hi PmenuSbar guifg=NONE guibg=#1f252f guisp=NONE gui=NONE ctermfg=NONE ctermbg=235 cterm=NONE
hi PmenuThumb guifg=NONE guibg=#373b41 guisp=NONE gui=NONE ctermfg=NONE ctermbg=237 cterm=NONE
hi WildMenu guifg=#ffffff guibg=#373b41 guisp=NONE gui=bold ctermfg=231 ctermbg=237 cterm=bold
hi StatusLine guifg=#c5c8c6 guibg=#1b2029 guisp=NONE gui=NONE ctermfg=251 ctermbg=235 cterm=NONE
hi StatusLineNC guifg=#7f7f7f guibg=#1b2029 guisp=NONE gui=NONE ctermfg=244 ctermbg=235 cterm=NONE
hi StatusLineTerm guifg=#c5c8c6 guibg=#1b2029 guisp=NONE gui=NONE ctermfg=251 ctermbg=235 cterm=NONE
hi StatusLineTermNC guifg=#7f7f7f guibg=#1b2029 guisp=NONE gui=NONE ctermfg=244 ctermbg=235 cterm=NONE
hi TabLine guifg=#7f7f7f guibg=#1f252f guisp=NONE gui=NONE ctermfg=244 ctermbg=235 cterm=NONE
hi TabLineFill guifg=NONE guibg=#1b2029 guisp=NONE gui=NONE ctermfg=NONE ctermbg=235 cterm=NONE
hi TabLineSel guifg=#ffffff guibg=#252c38 guisp=NONE gui=bold ctermfg=231 ctermbg=236 cterm=bold
hi Title guifg=#9ed1a0 guibg=NONE guisp=NONE gui=bold ctermfg=151 ctermbg=NONE cterm=bold
hi Directory guifg=#81a2be guibg=NONE guisp=NONE gui=NONE ctermfg=109 ctermbg=NONE cterm=NONE
hi QuickFixLine guifg=NONE guibg=#4c4f57 guisp=NONE gui=NONE ctermfg=NONE ctermbg=239 cterm=NONE
hi ErrorMsg guifg=#fda1aa guibg=NONE guisp=NONE gui=NONE ctermfg=217 ctermbg=NONE cterm=NONE
hi WarningMsg guifg=#f0c674 guibg=NONE guisp=NONE gui=NONE ctermfg=222 ctermbg=NONE cterm=NONE
hi ModeMsg guifg=#9ed1a0 guibg=NONE guisp=NONE gui=bold ctermfg=151 ctermbg=NONE cterm=bold
hi MoreMsg guifg=#9ed1a0 guibg=NONE guisp=NONE gui=NONE ctermfg=151 ctermbg=NONE cterm=NONE
hi Question guifg=#a4d8d1 guibg=NONE guisp=NONE gui=NONE ctermfg=152 ctermbg=NONE cterm=NONE
hi SpellBad guifg=NONE guibg=NONE guisp=#fda1aa gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
hi SpellCap guifg=NONE guibg=NONE guisp=#f0c674 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
hi SpellLocal guifg=NONE guibg=NONE guisp=#a4d8d1 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
hi SpellRare guifg=NONE guibg=NONE guisp=#81a2be gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
hi DiffAdd guifg=NONE guibg=#374548 guisp=NONE gui=NONE ctermfg=NONE ctermbg=238 cterm=NONE
hi DiffChange guifg=NONE guibg=#393b3e guisp=NONE gui=NONE ctermfg=NONE ctermbg=237 cterm=NONE
hi DiffDelete guifg=#fda1aa guibg=#453e49 guisp=NONE gui=NONE ctermfg=217 ctermbg=238 cterm=NONE
hi DiffText guifg=NONE guibg=#585247 guisp=NONE gui=NONE ctermfg=NONE ctermbg=239 cterm=NONE
hi Added guifg=#9ed1a0 guibg=NONE guisp=NONE gui=NONE ctermfg=151 ctermbg=NONE cterm=NONE
hi Changed guifg=#f0c674 guibg=NONE guisp=NONE gui=NONE ctermfg=222 ctermbg=NONE cterm=NONE
hi Removed guifg=#dc143c guibg=NONE guisp=NONE gui=NONE ctermfg=161 ctermbg=NONE cterm=NONE
hi Comment guifg=#7f7f7f guibg=NONE guisp=NONE gui=italic ctermfg=244 ctermbg=NONE cterm=italic
hi Constant guifg=#ffffff guibg=NONE guisp=NONE gui=NONE ctermfg=231 ctermbg=NONE cterm=NONE
hi String guifg=#9ed1a0 guibg=NONE guisp=NONE gui=NONE ctermfg=151 ctermbg=NONE cterm=NONE
hi Character guifg=#9ed1a0 guibg=NONE guisp=NONE gui=NONE ctermfg=151 ctermbg=NONE cterm=NONE
hi Number guifg=#83c6d5 guibg=NONE guisp=NONE gui=NONE ctermfg=116 ctermbg=NONE cterm=NONE
hi Float guifg=#83c6d5 guibg=NONE guisp=NONE gui=NONE ctermfg=116 ctermbg=NONE cterm=NONE
hi Boolean guifg=#ffffff guibg=NONE guisp=NONE gui=NONE ctermfg=231 ctermbg=NONE cterm=NONE
hi Identifier guifg=#fda1aa guibg=NONE guisp=NONE gui=NONE ctermfg=217 ctermbg=NONE cterm=NONE
hi Function guifg=#81a2be guibg=NONE guisp=NONE gui=NONE ctermfg=109 ctermbg=NONE cterm=NONE
hi Statement guifg=#969896 guibg=NONE guisp=NONE gui=NONE ctermfg=246 ctermbg=NONE cterm=NONE
hi Conditional guifg=#969896 guibg=NONE guisp=NONE gui=NONE ctermfg=246 ctermbg=NONE cterm=NONE
hi Repeat guifg=#969896 guibg=NONE guisp=NONE gui=NONE ctermfg=246 ctermbg=NONE cterm=NONE
hi Label guifg=#969896 guibg=NONE guisp=NONE gui=NONE ctermfg=246 ctermbg=NONE cterm=NONE
hi Keyword guifg=#969896 guibg=NONE guisp=NONE gui=NONE ctermfg=246 ctermbg=NONE cterm=NONE
hi Exception guifg=#969896 guibg=NONE guisp=NONE gui=NONE ctermfg=246 ctermbg=NONE cterm=NONE
hi Operator guifg=#ffe2a1 guibg=NONE guisp=NONE gui=NONE ctermfg=223 ctermbg=NONE cterm=NONE
hi PreProc guifg=#969896 guibg=NONE guisp=NONE gui=NONE ctermfg=246 ctermbg=NONE cterm=NONE
hi Include guifg=#81a2be guibg=NONE guisp=NONE gui=NONE ctermfg=109 ctermbg=NONE cterm=NONE
hi Define guifg=#969896 guibg=NONE guisp=NONE gui=NONE ctermfg=246 ctermbg=NONE cterm=NONE
hi Macro guifg=#a4d8d1 guibg=NONE guisp=NONE gui=NONE ctermfg=152 ctermbg=NONE cterm=NONE
hi PreCondit guifg=#969896 guibg=NONE guisp=NONE gui=NONE ctermfg=246 ctermbg=NONE cterm=NONE
hi Type guifg=#f0c674 guibg=NONE guisp=NONE gui=NONE ctermfg=222 ctermbg=NONE cterm=NONE
hi StorageClass guifg=#969896 guibg=NONE guisp=NONE gui=NONE ctermfg=246 ctermbg=NONE cterm=NONE
hi Structure guifg=#f0c674 guibg=NONE guisp=NONE gui=NONE ctermfg=222 ctermbg=NONE cterm=NONE
hi Typedef guifg=#f0c674 guibg=NONE guisp=NONE gui=NONE ctermfg=222 ctermbg=NONE cterm=NONE
hi Special guifg=#a4d8d1 guibg=NONE guisp=NONE gui=NONE ctermfg=152 ctermbg=NONE cterm=NONE
hi SpecialChar guifg=#a4d8d1 guibg=NONE guisp=NONE gui=NONE ctermfg=152 ctermbg=NONE cterm=NONE
hi Tag guifg=#fda1aa guibg=NONE guisp=NONE gui=underline ctermfg=217 ctermbg=NONE cterm=underline
hi Delimiter guifg=#c5c8c6 guibg=NONE guisp=NONE gui=NONE ctermfg=251 ctermbg=NONE cterm=NONE
hi SpecialComment guifg=#7f7f7f guibg=NONE guisp=NONE gui=italic ctermfg=244 ctermbg=NONE cterm=italic
hi Debug guifg=#fda1aa guibg=NONE guisp=NONE gui=NONE ctermfg=217 ctermbg=NONE cterm=NONE
hi Underlined guifg=#a4d8d1 guibg=NONE guisp=NONE gui=underline ctermfg=152 ctermbg=NONE cterm=underline
hi Ignore guifg=#7f7f7f guibg=NONE guisp=NONE gui=NONE ctermfg=244 ctermbg=NONE cterm=NONE
hi Error guifg=#252c38 guibg=#fda1aa guisp=NONE gui=NONE ctermfg=236 ctermbg=217 cterm=NONE
hi Todo guifg=#f0c674 guibg=NONE guisp=NONE gui=bold,italic ctermfg=222 ctermbg=NONE cterm=bold,italic
hi htmlTag guifg=#c5c8c6 guibg=NONE guisp=NONE gui=NONE ctermfg=251 ctermbg=NONE cterm=NONE
hi htmlEndTag guifg=#c5c8c6 guibg=NONE guisp=NONE gui=NONE ctermfg=251 ctermbg=NONE cterm=NONE
hi htmlTagName guifg=#fda1aa guibg=NONE guisp=NONE gui=underline ctermfg=217 ctermbg=NONE cterm=underline
hi htmlSpecialTagName guifg=#fda1aa guibg=NONE guisp=NONE gui=underline ctermfg=217 ctermbg=NONE cterm=underline
hi htmlArg guifg=#ffffff guibg=NONE guisp=NONE gui=NONE ctermfg=231 ctermbg=NONE cterm=NONE
hi htmlTitle guifg=#c5c8c6 guibg=NONE guisp=NONE gui=NONE ctermfg=251 ctermbg=NONE cterm=NONE
hi htmlH1 guifg=#9ed1a0 guibg=NONE guisp=NONE gui=bold ctermfg=151 ctermbg=NONE cterm=bold
hi xmlTag guifg=#c5c8c6 guibg=NONE guisp=NONE gui=NONE ctermfg=251 ctermbg=NONE cterm=NONE
hi xmlEndTag guifg=#c5c8c6 guibg=NONE guisp=NONE gui=NONE ctermfg=251 ctermbg=NONE cterm=NONE
hi xmlTagName guifg=#fda1aa guibg=NONE guisp=NONE gui=underline ctermfg=217 ctermbg=NONE cterm=underline
hi xmlAttrib guifg=#ffffff guibg=NONE guisp=NONE gui=NONE ctermfg=231 ctermbg=NONE cterm=NONE
hi cssClassName guifg=#f0c674 guibg=NONE guisp=NONE gui=NONE ctermfg=222 ctermbg=NONE cterm=NONE
hi cssIdentifier guifg=#81a2be guibg=NONE guisp=NONE gui=NONE ctermfg=109 ctermbg=NONE cterm=NONE
hi cssTagName guifg=#fda1aa guibg=NONE guisp=NONE gui=NONE ctermfg=217 ctermbg=NONE cterm=NONE
hi cssPseudoClassId guifg=#a4d8d1 guibg=NONE guisp=NONE gui=NONE ctermfg=152 ctermbg=NONE cterm=NONE
hi cssProp guifg=#c5c8c6 guibg=NONE guisp=NONE gui=NONE ctermfg=251 ctermbg=NONE cterm=NONE
hi cssAttr guifg=#ffffff guibg=NONE guisp=NONE gui=NONE ctermfg=231 ctermbg=NONE cterm=NONE
hi cssColor guifg=#a4d8d1 guibg=NONE guisp=NONE gui=NONE ctermfg=152 ctermbg=NONE cterm=NONE
hi cssUnitDecorators guifg=#ffffff guibg=NONE guisp=NONE gui=NONE ctermfg=231 ctermbg=NONE cterm=NONE
hi cssImportant guifg=#ffe2a1 guibg=NONE guisp=NONE gui=NONE ctermfg=223 ctermbg=NONE cterm=NONE
hi javaScriptIdentifier guifg=#969896 guibg=NONE guisp=NONE gui=NONE ctermfg=246 ctermbg=NONE cterm=NONE
hi javaScriptFunction guifg=#969896 guibg=NONE guisp=NONE gui=NONE ctermfg=246 ctermbg=NONE cterm=NONE
hi javaScriptMember guifg=#c5c8c6 guibg=NONE guisp=NONE gui=NONE ctermfg=251 ctermbg=NONE cterm=NONE
hi jsFunction guifg=#969896 guibg=NONE guisp=NONE gui=NONE ctermfg=246 ctermbg=NONE cterm=NONE
hi jsFuncName guifg=#81a2be guibg=NONE guisp=NONE gui=NONE ctermfg=109 ctermbg=NONE cterm=NONE
hi jsFuncCall guifg=#81a2be guibg=NONE guisp=NONE gui=NONE ctermfg=109 ctermbg=NONE cterm=NONE
hi jsFuncArgs guifg=#c5c8c6 guibg=NONE guisp=NONE gui=NONE ctermfg=251 ctermbg=NONE cterm=NONE
hi jsObjectKey guifg=#c5c8c6 guibg=NONE guisp=NONE gui=NONE ctermfg=251 ctermbg=NONE cterm=NONE
hi jsObjectProp guifg=#c5c8c6 guibg=NONE guisp=NONE gui=NONE ctermfg=251 ctermbg=NONE cterm=NONE
hi jsGlobalObjects guifg=#f0c674 guibg=NONE guisp=NONE gui=underline ctermfg=222 ctermbg=NONE cterm=underline
hi jsThis guifg=#fda1aa guibg=NONE guisp=NONE gui=NONE ctermfg=217 ctermbg=NONE cterm=NONE
hi jsStorageClass guifg=#969896 guibg=NONE guisp=NONE gui=NONE ctermfg=246 ctermbg=NONE cterm=NONE
hi jsExportDefault guifg=#fda1aa guibg=NONE guisp=NONE gui=NONE ctermfg=217 ctermbg=NONE cterm=NONE
hi jsDocTags guifg=#7f7f7f guibg=NONE guisp=NONE gui=italic ctermfg=244 ctermbg=NONE cterm=italic
hi jsDocType guifg=#f0c674 guibg=NONE guisp=NONE gui=italic,underline ctermfg=222 ctermbg=NONE cterm=italic,underline
hi jsDocParam guifg=#fda1aa guibg=NONE guisp=NONE gui=bold,italic ctermfg=217 ctermbg=NONE cterm=bold,italic
hi jsTemplateBraces guifg=#fc6f7d guibg=NONE guisp=NONE gui=NONE ctermfg=204 ctermbg=NONE cterm=NONE
hi phpVarSelector guifg=#fda1aa guibg=NONE guisp=NONE gui=NONE ctermfg=217 ctermbg=NONE cterm=NONE
hi phpIdentifier guifg=#fda1aa guibg=NONE guisp=NONE gui=NONE ctermfg=217 ctermbg=NONE cterm=NONE
hi phpMethodsVar guifg=#c5c8c6 guibg=NONE guisp=NONE gui=NONE ctermfg=251 ctermbg=NONE cterm=NONE
hi markdownH1 guifg=#9ed1a0 guibg=NONE guisp=NONE gui=bold ctermfg=151 ctermbg=NONE cterm=bold
hi markdownH2 guifg=#9ed1a0 guibg=NONE guisp=NONE gui=bold ctermfg=151 ctermbg=NONE cterm=bold
hi markdownH3 guifg=#9ed1a0 guibg=NONE guisp=NONE gui=NONE ctermfg=151 ctermbg=NONE cterm=NONE
hi markdownHeadingDelimiter guifg=#81a2be guibg=NONE guisp=NONE gui=NONE ctermfg=109 ctermbg=NONE cterm=NONE
hi markdownBold guifg=#ffffff guibg=NONE guisp=NONE gui=bold ctermfg=231 ctermbg=NONE cterm=bold
hi markdownItalic guifg=#969896 guibg=NONE guisp=NONE gui=italic ctermfg=246 ctermbg=NONE cterm=italic
hi markdownCode guifg=#9ed1a0 guibg=NONE guisp=NONE gui=NONE ctermfg=151 ctermbg=NONE cterm=NONE
hi markdownCodeBlock guifg=#9ed1a0 guibg=NONE guisp=NONE gui=NONE ctermfg=151 ctermbg=NONE cterm=NONE
hi markdownListMarker guifg=#fda1aa guibg=NONE guisp=NONE gui=NONE ctermfg=217 ctermbg=NONE cterm=NONE
hi markdownBlockquote guifg=#ffffff guibg=NONE guisp=NONE gui=NONE ctermfg=231 ctermbg=NONE cterm=NONE
hi markdownLinkText guifg=#fda1aa guibg=NONE guisp=NONE gui=NONE ctermfg=217 ctermbg=NONE cterm=NONE
hi markdownUrl guifg=#a4d8d1 guibg=NONE guisp=NONE gui=underline ctermfg=152 ctermbg=NONE cterm=underline
hi diffAdded guifg=#9ed1a0 guibg=NONE guisp=NONE gui=NONE ctermfg=151 ctermbg=NONE cterm=NONE
hi diffRemoved guifg=#fda1aa guibg=NONE guisp=NONE gui=NONE ctermfg=217 ctermbg=NONE cterm=NONE
hi diffChanged guifg=#f0c674 guibg=NONE guisp=NONE gui=NONE ctermfg=222 ctermbg=NONE cterm=NONE
hi diffFile guifg=#81a2be guibg=NONE guisp=NONE gui=NONE ctermfg=109 ctermbg=NONE cterm=NONE
hi diffLine guifg=#a4d8d1 guibg=NONE guisp=NONE gui=NONE ctermfg=152 ctermbg=NONE cterm=NONE
hi gitcommitSummary guifg=#c5c8c6 guibg=NONE guisp=NONE gui=NONE ctermfg=251 ctermbg=NONE cterm=NONE
hi GitGutterAdd guifg=#9ed1a0 guibg=#252c38 guisp=NONE gui=NONE ctermfg=151 ctermbg=236 cterm=NONE
hi GitGutterChange guifg=#f0c674 guibg=#252c38 guisp=NONE gui=NONE ctermfg=222 ctermbg=236 cterm=NONE
hi GitGutterDelete guifg=#dc143c guibg=#252c38 guisp=NONE gui=NONE ctermfg=161 ctermbg=236 cterm=NONE
hi SignifySignAdd guifg=#9ed1a0 guibg=#252c38 guisp=NONE gui=NONE ctermfg=151 ctermbg=236 cterm=NONE
hi SignifySignChange guifg=#f0c674 guibg=#252c38 guisp=NONE gui=NONE ctermfg=222 ctermbg=236 cterm=NONE
hi SignifySignDelete guifg=#dc143c guibg=#252c38 guisp=NONE gui=NONE ctermfg=161 ctermbg=236 cterm=NONE

if has('nvim')
  hi DiagnosticError guifg=#fda1aa guibg=NONE guisp=NONE gui=NONE ctermfg=217 ctermbg=NONE cterm=NONE
  hi DiagnosticWarn guifg=#f0c674 guibg=NONE guisp=NONE gui=NONE ctermfg=222 ctermbg=NONE cterm=NONE
  hi DiagnosticInfo guifg=#81a2be guibg=NONE guisp=NONE gui=NONE ctermfg=109 ctermbg=NONE cterm=NONE
  hi DiagnosticHint guifg=#a4d8d1 guibg=NONE guisp=NONE gui=NONE ctermfg=152 ctermbg=NONE cterm=NONE
  hi DiagnosticOk guifg=#9ed1a0 guibg=NONE guisp=NONE gui=NONE ctermfg=151 ctermbg=NONE cterm=NONE
  hi DiagnosticUnderlineError guifg=NONE guibg=NONE guisp=#fda1aa gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi DiagnosticUnderlineWarn guifg=NONE guibg=NONE guisp=#f0c674 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi DiagnosticUnderlineInfo guifg=NONE guibg=NONE guisp=#81a2be gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi DiagnosticUnderlineHint guifg=NONE guibg=NONE guisp=#a4d8d1 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi DiagnosticVirtualTextError guifg=#fda1aa guibg=#3b3843 guisp=NONE gui=NONE ctermfg=217 ctermbg=237 cterm=NONE
  hi DiagnosticVirtualTextWarn guifg=#f0c674 guibg=#393b3e guisp=NONE gui=NONE ctermfg=222 ctermbg=237 cterm=NONE
  hi DiagnosticVirtualTextInfo guifg=#81a2be guibg=#2e3845 guisp=NONE gui=NONE ctermfg=109 ctermbg=237 cterm=NONE
  hi DiagnosticVirtualTextHint guifg=#a4d8d1 guibg=#323d47 guisp=NONE gui=NONE ctermfg=152 ctermbg=237 cterm=NONE
  hi LspReferenceText guifg=NONE guibg=#374453 guisp=NONE gui=NONE ctermfg=NONE ctermbg=238 cterm=NONE
  hi LspReferenceRead guifg=NONE guibg=#374453 guisp=NONE gui=NONE ctermfg=NONE ctermbg=238 cterm=NONE
  hi LspReferenceWrite guifg=NONE guibg=#414f60 guisp=NONE gui=NONE ctermfg=NONE ctermbg=239 cterm=NONE
  hi LspInlayHint guifg=#7f7f7f guibg=#2e343d guisp=NONE gui=NONE ctermfg=244 ctermbg=236 cterm=NONE
  hi WinBar guifg=#969896 guibg=NONE guisp=NONE gui=NONE ctermfg=246 ctermbg=NONE cterm=NONE
  hi WinBarNC guifg=#7f7f7f guibg=NONE guisp=NONE gui=NONE ctermfg=244 ctermbg=NONE cterm=NONE
  hi @variable guifg=#c5c8c6 guibg=NONE guisp=NONE gui=NONE ctermfg=251 ctermbg=NONE cterm=NONE
  hi @variable.builtin guifg=#fda1aa guibg=NONE guisp=NONE gui=NONE ctermfg=217 ctermbg=NONE cterm=NONE
  hi @variable.parameter guifg=#c5c8c6 guibg=NONE guisp=NONE gui=NONE ctermfg=251 ctermbg=NONE cterm=NONE
  hi @variable.member guifg=#c5c8c6 guibg=NONE guisp=NONE gui=NONE ctermfg=251 ctermbg=NONE cterm=NONE
  hi @property guifg=#c5c8c6 guibg=NONE guisp=NONE gui=NONE ctermfg=251 ctermbg=NONE cterm=NONE
  hi @constant guifg=#ffffff guibg=NONE guisp=NONE gui=NONE ctermfg=231 ctermbg=NONE cterm=NONE
  hi @constant.builtin guifg=#ffffff guibg=NONE guisp=NONE gui=NONE ctermfg=231 ctermbg=NONE cterm=NONE
  hi @module guifg=#f0c674 guibg=NONE guisp=NONE gui=NONE ctermfg=222 ctermbg=NONE cterm=NONE
  hi @label guifg=#81a2be guibg=NONE guisp=NONE gui=NONE ctermfg=109 ctermbg=NONE cterm=NONE
  hi @string guifg=#9ed1a0 guibg=NONE guisp=NONE gui=NONE ctermfg=151 ctermbg=NONE cterm=NONE
  hi @string.escape guifg=#a4d8d1 guibg=NONE guisp=NONE gui=NONE ctermfg=152 ctermbg=NONE cterm=NONE
  hi @string.regexp guifg=#a4d8d1 guibg=NONE guisp=NONE gui=NONE ctermfg=152 ctermbg=NONE cterm=NONE
  hi @string.special guifg=#a4d8d1 guibg=NONE guisp=NONE gui=NONE ctermfg=152 ctermbg=NONE cterm=NONE
  hi @string.special.symbol guifg=#9ed1a0 guibg=NONE guisp=NONE gui=NONE ctermfg=151 ctermbg=NONE cterm=NONE
  hi @string.special.url guifg=#a4d8d1 guibg=NONE guisp=NONE gui=underline ctermfg=152 ctermbg=NONE cterm=underline
  hi @character guifg=#9ed1a0 guibg=NONE guisp=NONE gui=NONE ctermfg=151 ctermbg=NONE cterm=NONE
  hi @number guifg=#83c6d5 guibg=NONE guisp=NONE gui=NONE ctermfg=116 ctermbg=NONE cterm=NONE
  hi @boolean guifg=#ffffff guibg=NONE guisp=NONE gui=NONE ctermfg=231 ctermbg=NONE cterm=NONE
  hi @type guifg=#f0c674 guibg=NONE guisp=NONE gui=underline ctermfg=222 ctermbg=NONE cterm=underline
  hi @type.builtin guifg=#f0c674 guibg=NONE guisp=NONE gui=underline ctermfg=222 ctermbg=NONE cterm=underline
  hi @type.definition guifg=#f0c674 guibg=NONE guisp=NONE gui=NONE ctermfg=222 ctermbg=NONE cterm=NONE
  hi @attribute guifg=#ffffff guibg=NONE guisp=NONE gui=NONE ctermfg=231 ctermbg=NONE cterm=NONE
  hi @function guifg=#81a2be guibg=NONE guisp=NONE gui=NONE ctermfg=109 ctermbg=NONE cterm=NONE
  hi @function.call guifg=#81a2be guibg=NONE guisp=NONE gui=NONE ctermfg=109 ctermbg=NONE cterm=NONE
  hi @function.builtin guifg=#a4d8d1 guibg=NONE guisp=NONE gui=NONE ctermfg=152 ctermbg=NONE cterm=NONE
  hi @function.method guifg=#81a2be guibg=NONE guisp=NONE gui=NONE ctermfg=109 ctermbg=NONE cterm=NONE
  hi @function.method.call guifg=#81a2be guibg=NONE guisp=NONE gui=NONE ctermfg=109 ctermbg=NONE cterm=NONE
  hi @constructor guifg=#f0c674 guibg=NONE guisp=NONE gui=underline ctermfg=222 ctermbg=NONE cterm=underline
  hi @operator guifg=#ffe2a1 guibg=NONE guisp=NONE gui=NONE ctermfg=223 ctermbg=NONE cterm=NONE
  hi @keyword guifg=#969896 guibg=NONE guisp=NONE gui=NONE ctermfg=246 ctermbg=NONE cterm=NONE
  hi @keyword.operator guifg=#ffe2a1 guibg=NONE guisp=NONE gui=NONE ctermfg=223 ctermbg=NONE cterm=NONE
  hi @keyword.import guifg=#969896 guibg=NONE guisp=NONE gui=NONE ctermfg=246 ctermbg=NONE cterm=NONE
  hi @keyword.export guifg=#969896 guibg=NONE guisp=NONE gui=NONE ctermfg=246 ctermbg=NONE cterm=NONE
  hi @punctuation guifg=#c5c8c6 guibg=NONE guisp=NONE gui=NONE ctermfg=251 ctermbg=NONE cterm=NONE
  hi @punctuation.special guifg=#fc6f7d guibg=NONE guisp=NONE gui=NONE ctermfg=204 ctermbg=NONE cterm=NONE
  hi @comment guifg=#7f7f7f guibg=NONE guisp=NONE gui=italic ctermfg=244 ctermbg=NONE cterm=italic
  hi @comment.documentation guifg=#7f7f7f guibg=NONE guisp=NONE gui=italic ctermfg=244 ctermbg=NONE cterm=italic
  hi @comment.todo guifg=#f0c674 guibg=NONE guisp=NONE gui=bold,italic ctermfg=222 ctermbg=NONE cterm=bold,italic
  hi @tag guifg=#fda1aa guibg=NONE guisp=NONE gui=underline ctermfg=217 ctermbg=NONE cterm=underline
  hi @tag.builtin guifg=#fda1aa guibg=NONE guisp=NONE gui=underline ctermfg=217 ctermbg=NONE cterm=underline
  hi @tag.attribute guifg=#ffffff guibg=NONE guisp=NONE gui=NONE ctermfg=231 ctermbg=NONE cterm=NONE
  hi @tag.delimiter guifg=#c5c8c6 guibg=NONE guisp=NONE gui=NONE ctermfg=251 ctermbg=NONE cterm=NONE
  hi @markup.heading guifg=#9ed1a0 guibg=NONE guisp=NONE gui=bold ctermfg=151 ctermbg=NONE cterm=bold
  hi @markup.strong guifg=#ffffff guibg=NONE guisp=NONE gui=bold ctermfg=231 ctermbg=NONE cterm=bold
  hi @markup.italic guifg=#969896 guibg=NONE guisp=NONE gui=italic ctermfg=246 ctermbg=NONE cterm=italic
  hi @markup.strikethrough guifg=#969896 guibg=NONE guisp=NONE gui=strikethrough ctermfg=246 ctermbg=NONE cterm=strikethrough
  hi @markup.raw guifg=#9ed1a0 guibg=NONE guisp=NONE gui=NONE ctermfg=151 ctermbg=NONE cterm=NONE
  hi @markup.quote guifg=#ffffff guibg=NONE guisp=NONE gui=NONE ctermfg=231 ctermbg=NONE cterm=NONE
  hi @markup.list guifg=#fda1aa guibg=NONE guisp=NONE gui=NONE ctermfg=217 ctermbg=NONE cterm=NONE
  hi @markup.link guifg=#fda1aa guibg=NONE guisp=NONE gui=NONE ctermfg=217 ctermbg=NONE cterm=NONE
  hi @markup.link.label guifg=#fda1aa guibg=NONE guisp=NONE gui=NONE ctermfg=217 ctermbg=NONE cterm=NONE
  hi @markup.link.url guifg=#a4d8d1 guibg=NONE guisp=NONE gui=underline ctermfg=152 ctermbg=NONE cterm=underline
  hi @diff.plus guifg=#9ed1a0 guibg=NONE guisp=NONE gui=NONE ctermfg=151 ctermbg=NONE cterm=NONE
  hi @diff.minus guifg=#fda1aa guibg=NONE guisp=NONE gui=NONE ctermfg=217 ctermbg=NONE cterm=NONE
  hi @diff.delta guifg=#f0c674 guibg=NONE guisp=NONE gui=NONE ctermfg=222 ctermbg=NONE cterm=NONE
  hi @lsp.type.class guifg=#f0c674 guibg=NONE guisp=NONE gui=NONE ctermfg=222 ctermbg=NONE cterm=NONE
  hi @lsp.type.interface guifg=#f0c674 guibg=NONE guisp=NONE gui=NONE ctermfg=222 ctermbg=NONE cterm=NONE
  hi @lsp.type.enum guifg=#f0c674 guibg=NONE guisp=NONE gui=NONE ctermfg=222 ctermbg=NONE cterm=NONE
  hi @lsp.type.enumMember guifg=#ffffff guibg=NONE guisp=NONE gui=NONE ctermfg=231 ctermbg=NONE cterm=NONE
  hi @lsp.type.namespace guifg=#f0c674 guibg=NONE guisp=NONE gui=NONE ctermfg=222 ctermbg=NONE cterm=NONE
  hi @lsp.type.parameter guifg=#c5c8c6 guibg=NONE guisp=NONE gui=NONE ctermfg=251 ctermbg=NONE cterm=NONE
  hi @lsp.type.property guifg=#c5c8c6 guibg=NONE guisp=NONE gui=NONE ctermfg=251 ctermbg=NONE cterm=NONE
  hi @lsp.type.variable guifg=#c5c8c6 guibg=NONE guisp=NONE gui=NONE ctermfg=251 ctermbg=NONE cterm=NONE
  hi @lsp.typemod.variable.defaultLibrary guifg=#fda1aa guibg=NONE guisp=NONE gui=NONE ctermfg=217 ctermbg=NONE cterm=NONE
  hi @lsp.typemod.function.defaultLibrary guifg=#a4d8d1 guibg=NONE guisp=NONE gui=NONE ctermfg=152 ctermbg=NONE cterm=NONE
  hi GitSignsAdd guifg=#9ed1a0 guibg=#252c38 guisp=NONE gui=NONE ctermfg=151 ctermbg=236 cterm=NONE
  hi GitSignsChange guifg=#f0c674 guibg=#252c38 guisp=NONE gui=NONE ctermfg=222 ctermbg=236 cterm=NONE
  hi GitSignsDelete guifg=#dc143c guibg=#252c38 guisp=NONE gui=NONE ctermfg=161 ctermbg=236 cterm=NONE
  hi TelescopeBorder guifg=#373b41 guibg=#1f252f guisp=NONE gui=NONE ctermfg=237 ctermbg=235 cterm=NONE
  hi TelescopeNormal guifg=#c5c8c6 guibg=#1f252f guisp=NONE gui=NONE ctermfg=251 ctermbg=235 cterm=NONE
  hi TelescopeSelection guifg=#ffffff guibg=#373b41 guisp=NONE gui=NONE ctermfg=231 ctermbg=237 cterm=NONE
  hi TelescopeMatching guifg=#a4d8d1 guibg=NONE guisp=NONE gui=bold ctermfg=152 ctermbg=NONE cterm=bold
  hi NvimTreeNormal guifg=#969896 guibg=#1f252f guisp=NONE gui=NONE ctermfg=246 ctermbg=235 cterm=NONE
  hi NvimTreeFolderName guifg=#81a2be guibg=NONE guisp=NONE gui=NONE ctermfg=109 ctermbg=NONE cterm=NONE
  hi NvimTreeOpenedFolderName guifg=#81a2be guibg=NONE guisp=NONE gui=bold ctermfg=109 ctermbg=NONE cterm=bold
  hi NeoTreeNormal guifg=#969896 guibg=#1f252f guisp=NONE gui=NONE ctermfg=246 ctermbg=235 cterm=NONE
  hi NeoTreeNormalNC guifg=#969896 guibg=#1f252f guisp=NONE gui=NONE ctermfg=246 ctermbg=235 cterm=NONE
  hi IblIndent guifg=#373b41 guibg=NONE guisp=NONE gui=NONE ctermfg=237 ctermbg=NONE cterm=NONE
  hi IblScope guifg=#7f7f7f guibg=NONE guisp=NONE gui=NONE ctermfg=244 ctermbg=NONE cterm=NONE
  hi RainbowDelimiterYellow guifg=#ffe2a1 guibg=NONE guisp=NONE gui=NONE ctermfg=223 ctermbg=NONE cterm=NONE
  hi RainbowDelimiterCyan guifg=#a4d8d1 guibg=NONE guisp=NONE gui=NONE ctermfg=152 ctermbg=NONE cterm=NONE
  hi RainbowDelimiterRed guifg=#fda1aa guibg=NONE guisp=NONE gui=NONE ctermfg=217 ctermbg=NONE cterm=NONE
  hi RainbowDelimiterBlue guifg=#81a2be guibg=NONE guisp=NONE gui=NONE ctermfg=109 ctermbg=NONE cterm=NONE
  hi RainbowDelimiterGreen guifg=#9ed1a0 guibg=NONE guisp=NONE gui=NONE ctermfg=151 ctermbg=NONE cterm=NONE
  hi RainbowDelimiterOrange guifg=#f0c674 guibg=NONE guisp=NONE gui=NONE ctermfg=222 ctermbg=NONE cterm=NONE

  let g:terminal_color_0 = '#282a2e'
  let g:terminal_color_1 = '#fda1aa'
  let g:terminal_color_2 = '#9ed1a0'
  let g:terminal_color_3 = '#f0c674'
  let g:terminal_color_4 = '#81a2be'
  let g:terminal_color_5 = '#d7a8d8'
  let g:terminal_color_6 = '#a4d8d1'
  let g:terminal_color_7 = '#c5c8c6'
  let g:terminal_color_8 = '#7f7f7f'
  let g:terminal_color_9 = '#ffbfc5'
  let g:terminal_color_10 = '#b9e3bb'
  let g:terminal_color_11 = '#ffe2a1'
  let g:terminal_color_12 = '#83c6d5'
  let g:terminal_color_13 = '#e8c6e9'
  let g:terminal_color_14 = '#c3e8e3'
  let g:terminal_color_15 = '#ffffff'
else
  let g:terminal_ansi_colors = [
        \ '#282a2e',
        \ '#fda1aa',
        \ '#9ed1a0',
        \ '#f0c674',
        \ '#81a2be',
        \ '#d7a8d8',
        \ '#a4d8d1',
        \ '#c5c8c6',
        \ '#7f7f7f',
        \ '#ffbfc5',
        \ '#b9e3bb',
        \ '#ffe2a1',
        \ '#83c6d5',
        \ '#e8c6e9',
        \ '#c3e8e3',
        \ '#ffffff',
        \ ]
endif
