// Builds the VS Code color theme from the shared palette.

import { colors as c, syntax as s, ui } from "./palette.mjs";
import { alpha } from "./color.mjs";

const rule = (name, scope, foreground, fontStyle) => ({
  name,
  scope,
  settings: {
    ...(foreground && { foreground }),
    ...(fontStyle !== undefined && { fontStyle }),
  },
});

const tokenColors = [
  // Comments
  rule("Comment", ["comment", "punctuation.definition.comment"], c.lightGray, "italic"),
  rule("Doc comment tag", ["storage.type.class.jsdoc", "keyword.other.phpdoc", "storage.type.class.doxygen"], c.lightGray, "italic"),
  rule("Doc comment type", ["entity.name.type.instance.jsdoc", "entity.name.type.instance.phpdoc"], c.lightOrange, "italic underline"),
  rule("Doc comment variable", ["variable.other.jsdoc", "variable.other.phpdoc"], c.red, "italic bold"),

  // Keywords & storage
  rule("Keyword", ["keyword", "keyword.control", "storage", "storage.type", "storage.modifier"], c.middleGray),
  rule("Keyword operator", ["keyword.operator", "keyword.operator.new", "keyword.operator.expression"], c.newOrange),
  rule("Keyword default export", ["keyword.control.default"], c.red),
  rule("Special method", ["keyword.other.special-method"], c.blue),
  rule("Unit", ["keyword.other.unit"], c.white),

  // Constants
  rule("Constant", ["constant", "constant.language", "support.constant"], c.white),
  rule("Escape character", ["constant.character.escape"], c.cyan),
  rule("Number", ["constant.numeric"], c.trueBlue),
  rule("Color", ["constant.other.color"], c.cyan),
  rule("Symbol", ["constant.other.symbol"], c.green),

  // Variables
  rule("Variable", ["variable", "variable.other.object", "variable.language", "variable.other.object.property"], c.red),
  rule(
    "Plain identifiers",
    [
      "variable.other.readwrite",
      "variable.other.constant",
      "variable.other.property",
      "variable.parameter",
      "variable.parameter.function",
      "meta.object-literal.key",
      "meta.definition.variable variable.other",
    ],
    s.text,
  ),
  rule("Interpolation", ["variable.interpolation", "punctuation.section.embedded", "punctuation.definition.template-expression"], s.redDark),
  // Atom used a red background here; VS Code token rules can't set backgrounds.
  rule("Invalid", ["invalid", "invalid.illegal"], c.red, "underline"),

  // Strings
  rule("String", ["string", "string.quoted", "string.template"], c.green),
  rule("Regexp", ["string.regexp"], c.cyan),
  rule("Link", ["string.other.link"], c.red),

  // Punctuation
  rule(
    "Punctuation definition",
    [
      "punctuation.definition.string",
      "punctuation.definition.variable",
      "punctuation.definition.parameters",
      "punctuation.definition.array",
    ],
    s.text,
  ),
  rule("Heading / identity punctuation", ["punctuation.definition.heading", "punctuation.definition.identity"], c.blue),
  rule("Bold punctuation", ["punctuation.definition.bold"], c.lightOrange, "bold"),
  rule("Italic punctuation", ["punctuation.definition.italic"], c.middleGray, "italic"),

  // Support
  rule("Support class", ["support.class", "support.type", "entity.name.type.class"], c.lightOrange),
  rule("Support function", ["support.function"], c.cyan),
  rule("Method", ["support.function.any-method", "meta.function-call entity.name.function", "entity.name.function"], c.blue),

  // Entities
  rule("Type", ["entity.name.type", "new.expr entity.name.type", "meta.function-call support.class", "new.expr support.class"], c.lightOrange, "underline"),
  rule("Class name", ["entity.name.class", "entity.name.type.class"], c.lightOrange, ""),
  rule("Inherited class", ["entity.other.inherited-class"], c.green),
  rule("Section", ["entity.name.section"], c.blue),
  rule("Tag", ["entity.name.tag", "support.class.component"], c.red, "underline"),
  rule("Tag punctuation", ["punctuation.definition.tag"], s.text),
  rule("Attribute name", ["entity.other.attribute-name"], c.white),
  rule("Attribute id", ["entity.other.attribute-name.id"], c.blue),
  rule("CSS class selector", ["entity.other.attribute-name.class.css", "entity.other.attribute-name.class"], c.lightOrange),
  rule("CSS pseudo", ["entity.other.attribute-name.pseudo-class", "entity.other.attribute-name.pseudo-element"], c.cyan),
  rule("CSS property", ["support.type.property-name", "support.type.vendored.property-name"], s.text),
  rule("CSS value", ["support.constant.property-value", "support.constant.font-name"], c.white),

  // Meta
  rule("Meta class", ["meta.class"], c.lightOrange),
  rule("Meta link", ["meta.link"], c.white),
  rule("Meta require", ["meta.require"], c.blue),
  rule("Meta selector", ["meta.selector"], c.middleGray),
  rule("Meta separator", ["meta.separator"], s.text),
  rule("None", ["none", "source", "meta.embedded"], s.text),

  // Markup
  rule("Markup bold", ["markup.bold"], c.white, "bold"),
  rule("Markup italic", ["markup.italic"], c.middleGray, "italic"),
  rule("Markup changed", ["markup.changed"], c.middleGray),
  rule("Markup deleted", ["markup.deleted"], c.red),
  rule("Markup inserted", ["markup.inserted"], c.green),
  rule("Markup heading", ["markup.heading", "markup.heading entity.name"], c.green),
  rule("Markup heading punctuation", ["markup.heading punctuation.definition.heading"], c.blue),
  rule("Markup list", ["markup.list", "punctuation.definition.list.begin.markdown"], c.red),
  rule("Markup quote", ["markup.quote"], c.white),
  rule("Markup raw", ["markup.raw.inline", "markup.inline.raw", "markup.fenced_code"], c.green),
  rule("Markup link", ["markup.underline.link"], c.cyan),
];

// Keep semantic highlighting (TypeScript, Rust, Go, …) aligned with the TextMate rules.
const semanticTokenColors = {
  variable: s.text,
  parameter: s.text,
  property: s.text,
  "variable.defaultLibrary": c.red,
  function: c.blue,
  method: c.blue,
  "function.defaultLibrary": c.cyan,
  "method.defaultLibrary": c.cyan,
  class: c.lightOrange,
  "class.defaultLibrary": { foreground: c.lightOrange, underline: true },
  type: { foreground: c.lightOrange, underline: true },
  interface: c.lightOrange,
  enum: c.lightOrange,
  enumMember: c.white,
  typeParameter: c.lightOrange,
  namespace: c.lightOrange,
  keyword: c.middleGray,
  number: c.trueBlue,
  string: c.green,
  regexp: c.cyan,
  macro: c.cyan,
  selfKeyword: c.red,
};

const ansi = {
  Black: c.darkGray,
  Red: c.red,
  Green: c.green,
  Yellow: c.lightOrange,
  Blue: c.blue,
  Magenta: "#d7a8d8",
  Cyan: c.cyan,
  White: c.veryLightGray,
  BrightBlack: c.lightGray,
  BrightRed: "#ffbfc5",
  BrightGreen: "#b9e3bb",
  BrightYellow: c.newOrange,
  BrightBlue: c.trueBlue,
  BrightMagenta: "#e8c6e9",
  BrightCyan: "#c3e8e3",
  BrightWhite: c.white,
};

const workbench = {
  focusBorder: alpha(c.cyan, 0.6),
  foreground: ui.fg,
  disabledForeground: ui.fgSubtle,
  descriptionForeground: ui.fgMuted,
  errorForeground: c.red,
  "icon.foreground": ui.fgMuted,
  "selection.background": ui.selection,
  "widget.shadow": "#00000055",
  "textLink.foreground": c.cyan,
  "textLink.activeForeground": c.trueBlue,
  "textPreformat.foreground": c.green,
  "textBlockQuote.background": ui.bgDark,
  "textBlockQuote.border": c.gray,
  "textCodeBlock.background": ui.bgDark,

  // Editor
  "editor.background": s.background,
  "editor.foreground": s.text,
  "editorCursor.foreground": s.cursor,
  "editor.selectionBackground": s.selection,
  "editor.inactiveSelectionBackground": alpha(s.selection, 0.6),
  "editor.selectionHighlightBackground": alpha(s.selection, 0.55),
  "editor.lineHighlightBackground": ui.lineHighlight,
  "editor.lineHighlightBorder": "#00000000",
  "editor.findMatchBackground": ui.findMatch,
  "editor.findMatchHighlightBackground": ui.findMatchHighlight,
  "editor.findRangeHighlightBackground": alpha(c.gray, 0.4),
  "editor.wordHighlightBackground": ui.wordHighlight,
  "editor.wordHighlightStrongBackground": ui.wordHighlightStrong,
  "editor.rangeHighlightBackground": alpha(c.gray, 0.4),
  "editorLineNumber.foreground": alpha(s.gutterText, 0.45),
  "editorLineNumber.activeForeground": s.gutterTextSelected,
  "editorGutter.background": s.gutterBackground,
  "editorGutter.addedBackground": s.added,
  "editorGutter.modifiedBackground": s.modified,
  "editorGutter.deletedBackground": s.removed,
  "editorGutter.foldingControlForeground": c.lightGray,
  "editorIndentGuide.background1": s.indentGuide,
  "editorIndentGuide.activeBackground1": c.lightGray,
  "editorWhitespace.foreground": s.invisible,
  "editorRuler.foreground": s.wrapGuide,
  "editorBracketMatch.background": alpha(c.cyan, 0.15),
  "editorBracketMatch.border": alpha(c.cyan, 0.5),
  "editorBracketHighlight.foreground1": c.newOrange,
  "editorBracketHighlight.foreground2": c.cyan,
  "editorBracketHighlight.foreground3": c.red,
  "editorBracketHighlight.foreground4": c.blue,
  "editorBracketHighlight.foreground5": c.green,
  "editorBracketHighlight.foreground6": c.lightOrange,
  "editorBracketHighlight.unexpectedBracket.foreground": s.removed,
  "editorCodeLens.foreground": c.lightGray,
  "editorLink.activeForeground": c.cyan,
  "editorInlayHint.foreground": c.lightGray,
  "editorInlayHint.background": alpha(c.gray, 0.5),
  "editorError.foreground": c.red,
  "editorWarning.foreground": c.lightOrange,
  "editorInfo.foreground": c.blue,
  "editorHint.foreground": c.cyan,
  "editorOverviewRuler.border": "#00000000",
  "editorOverviewRuler.addedForeground": alpha(s.added, 0.7),
  "editorOverviewRuler.modifiedForeground": alpha(s.modified, 0.7),
  "editorOverviewRuler.deletedForeground": alpha(s.removed, 0.7),
  "editorOverviewRuler.errorForeground": c.red,
  "editorOverviewRuler.warningForeground": c.lightOrange,
  "editorOverviewRuler.findMatchForeground": alpha(c.newOrange, 0.6),

  // Widgets
  "editorWidget.background": ui.bgDark,
  "editorWidget.border": ui.border,
  "editorSuggestWidget.background": ui.bgDark,
  "editorSuggestWidget.border": ui.border,
  "editorSuggestWidget.selectedBackground": c.gray,
  "editorSuggestWidget.highlightForeground": c.cyan,
  "editorHoverWidget.background": ui.bgDark,
  "editorHoverWidget.border": ui.border,
  "peekView.border": c.cyan,
  "peekViewEditor.background": ui.bgDark,
  "peekViewResult.background": ui.bgDarker,
  "peekViewTitle.background": ui.bgDarker,
  "peekViewEditor.matchHighlightBackground": ui.findMatch,
  "peekViewResult.matchHighlightBackground": ui.findMatch,
  "peekViewResult.selectionBackground": c.gray,

  // Diff
  "diffEditor.insertedTextBackground": alpha(c.green, 0.15),
  "diffEditor.removedTextBackground": alpha(c.red, 0.15),
  "diffEditor.insertedLineBackground": alpha(c.green, 0.08),
  "diffEditor.removedLineBackground": alpha(c.red, 0.08),

  // Workbench chrome
  "activityBar.background": ui.bgDarker,
  "activityBar.foreground": ui.fg,
  "activityBar.inactiveForeground": ui.fgSubtle,
  "activityBar.border": ui.border,
  "activityBar.activeBorder": c.cyan,
  "activityBarBadge.background": c.red,
  "activityBarBadge.foreground": s.background,
  "sideBar.background": ui.bgDark,
  "sideBar.foreground": ui.fgMuted,
  "sideBar.border": ui.border,
  "sideBarTitle.foreground": ui.fg,
  "sideBarSectionHeader.background": ui.bgDark,
  "sideBarSectionHeader.foreground": ui.fg,
  "sideBarSectionHeader.border": ui.border,
  "list.activeSelectionBackground": c.gray,
  "list.activeSelectionForeground": c.white,
  "list.inactiveSelectionBackground": alpha(c.gray, 0.7),
  "list.hoverBackground": alpha(c.gray, 0.5),
  "list.focusOutline": alpha(c.cyan, 0.6),
  "list.highlightForeground": c.cyan,
  "list.errorForeground": c.red,
  "list.warningForeground": c.lightOrange,
  "tree.indentGuidesStroke": c.gray,
  "editorGroup.border": ui.border,
  "editorGroupHeader.tabsBackground": ui.bgDark,
  "editorGroupHeader.tabsBorder": ui.border,
  "tab.activeBackground": s.background,
  "tab.activeForeground": c.white,
  "tab.activeBorderTop": c.red,
  "tab.inactiveBackground": ui.bgDark,
  "tab.inactiveForeground": ui.fgSubtle,
  "tab.border": ui.border,
  "tab.hoverBackground": s.background,
  "tab.unfocusedActiveForeground": ui.fgMuted,
  "breadcrumb.foreground": ui.fgSubtle,
  "breadcrumb.focusForeground": ui.fg,
  "breadcrumb.background": s.background,
  "titleBar.activeBackground": ui.bgDarker,
  "titleBar.activeForeground": ui.fg,
  "titleBar.inactiveBackground": ui.bgDarker,
  "titleBar.inactiveForeground": ui.fgSubtle,
  "titleBar.border": ui.border,
  "statusBar.background": ui.bgDarker,
  "statusBar.foreground": ui.fgMuted,
  "statusBar.border": ui.border,
  "statusBar.debuggingBackground": c.lightOrange,
  "statusBar.debuggingForeground": s.background,
  "statusBar.noFolderBackground": ui.bgDarker,
  "statusBarItem.remoteBackground": c.red,
  "statusBarItem.remoteForeground": s.background,
  "statusBarItem.hoverBackground": c.gray,
  "panel.background": ui.bgDark,
  "panel.border": ui.border,
  "panelTitle.activeBorder": c.red,
  "panelTitle.activeForeground": ui.fg,
  "panelTitle.inactiveForeground": ui.fgSubtle,
  "terminal.background": ui.bgDark,
  "terminal.foreground": s.text,
  "terminalCursor.foreground": s.cursor,
  "terminal.selectionBackground": s.selection,
  ...Object.fromEntries(Object.entries(ansi).map(([k, v]) => [`terminal.ansi${k}`, v])),

  // Inputs & buttons
  "input.background": ui.bgDarker,
  "input.foreground": ui.fg,
  "input.border": ui.border,
  "input.placeholderForeground": ui.fgSubtle,
  "inputOption.activeBorder": c.cyan,
  "inputValidation.errorBorder": c.red,
  "inputValidation.warningBorder": c.lightOrange,
  "inputValidation.infoBorder": c.blue,
  "dropdown.background": ui.bgDarker,
  "dropdown.border": ui.border,
  "dropdown.foreground": ui.fg,
  "button.background": c.cyan,
  "button.foreground": s.background,
  "button.hoverBackground": c.trueBlue,
  "button.secondaryBackground": c.gray,
  "button.secondaryForeground": ui.fg,
  "badge.background": c.gray,
  "badge.foreground": ui.fg,
  "progressBar.background": c.cyan,
  "scrollbar.shadow": "#00000033",
  "scrollbarSlider.background": alpha(c.gray, 0.6),
  "scrollbarSlider.hoverBackground": alpha(c.gray, 0.85),
  "scrollbarSlider.activeBackground": c.gray,
  "quickInput.background": ui.bgDark,
  "quickInputList.focusBackground": c.gray,
  "menu.background": ui.bgDark,
  "menu.selectionBackground": c.gray,
  "notifications.background": ui.bgDark,
  "notifications.border": ui.border,

  // Git decorations
  "gitDecoration.addedResourceForeground": s.added,
  "gitDecoration.untrackedResourceForeground": s.added,
  "gitDecoration.modifiedResourceForeground": s.modified,
  "gitDecoration.deletedResourceForeground": c.red,
  "gitDecoration.renamedResourceForeground": s.renamed,
  "gitDecoration.ignoredResourceForeground": c.lightGray,
  "gitDecoration.conflictingResourceForeground": c.red,
};

export function buildVSCodeTheme() {
  return {
    $schema: "vscode://schemas/color-theme",
    name: "Gobbie Gob Goo",
    type: "dark",
    semanticHighlighting: true,
    colors: workbench,
    semanticTokenColors,
    tokenColors,
  };
}
